//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Win32
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbRestoranEntities : DbContext
    {
        public dbRestoranEntities()
            : base("name=dbRestoranEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbBoylar> tbBoylar { get; set; }
        public virtual DbSet<tbFatura> tbFatura { get; set; }
        public virtual DbSet<tbFiyatlar> tbFiyatlar { get; set; }
        public virtual DbSet<tbGarson> tbGarson { get; set; }
        public virtual DbSet<tbHasilat> tbHasilat { get; set; }
        public virtual DbSet<tbIcecekler> tbIcecekler { get; set; }
        public virtual DbSet<tbMasalar> tbMasalar { get; set; }
        public virtual DbSet<tbMenu> tbMenu { get; set; }
        public virtual DbSet<tbMusteri> tbMusteri { get; set; }
        public virtual DbSet<tbPersonel> tbPersonel { get; set; }
        public virtual DbSet<tbSatis> tbSatis { get; set; }
        public virtual DbSet<tbSiparis> tbSiparis { get; set; }
        public virtual DbSet<tbSiparisDetay> tbSiparisDetay { get; set; }
        public virtual DbSet<tbSoslar> tbSoslar { get; set; }
        public virtual DbSet<tbYonetici> tbYonetici { get; set; }
    }
}
