//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Win32
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbFatura
    {
        public int ID { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<System.DateTime> FaturaTarihi { get; set; }
        public Nullable<int> FaturaTutari { get; set; }
        public string siparisDetay { get; set; }
    }
}
