//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Win32
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHasilat
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string MasaNo { get; set; }
        public string garsonNo { get; set; }
        public string odemeTuru { get; set; }
        public Nullable<int> toplamCiro { get; set; }
    }
}
