//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Win32
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMusteri
    {
        public int ID { get; set; }
        public string MusteriNo { get; set; }
        public string MusteriAdiSoyadi { get; set; }
        public string MusteriGsm { get; set; }
        public Nullable<System.DateTime> rezervasyonTarihi { get; set; }
    }
}
