//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Win32
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPersonel
    {
        public int ID { get; set; }
        public string PersonelNo { get; set; }
        public string PersonelAdiSoyadi { get; set; }
        public string PersonelTcKimlikNo { get; set; }
        public string PersonelGsmNo { get; set; }
        public Nullable<System.DateTime> IseGirisTarihi { get; set; }
        public Nullable<System.DateTime> IstenCikisTarihi { get; set; }
    }
}
