//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Win32
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSiparisDetay
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string siparisNo { get; set; }
        public string garsonNo { get; set; }
        public string masaNo { get; set; }
        public string siparisDetay { get; set; }
    
        public virtual tbGarson tbGarson { get; set; }
        public virtual tbYonetici tbYonetici { get; set; }
    }
}
