//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restoran.Win32
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSiparis
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string siparisNo { get; set; }
        public string garsonNo { get; set; }
        public string masaNo { get; set; }
        public string menu { get; set; }
        public string icecek { get; set; }
        public string sos { get; set; }
        public string boy { get; set; }
        public string notlar { get; set; }
        public string odemeTuru { get; set; }
        public Nullable<int> masaToplamTutar { get; set; }
    }
}
